# Generated by Django 4.2.1 on 2023-05-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0084_userprofile_formsubmission'),
        ('wagtailmailchimp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailchimpSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Mailchimp API Key ', max_length=50, null=True, verbose_name='Mailchimp API Key')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MailChimpApiContact',
        ),
        migrations.DeleteModel(
            name='MailingListSubscriptionPage',
        ),
    ]
