# Generated by Django 4.2.1 on 2023-05-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0085_remove_userprofile_user_delete_formsubmission_and_more'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSubscribePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('list_id', models.CharField(help_text='Enter the MailChimp list ID to use for this form', max_length=50, verbose_name='MailChimp List ID')),
                ('double_optin', models.BooleanField(default=True, help_text='Use double opt-in process for new subscribers', verbose_name='Double Opt-In')),
                ('thank_you_text', models.TextField(blank=True, help_text='Message to show on successful submission', null=True, verbose_name='Thank you text')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
