# Generated by Django 4.2.1 on 2023-07-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_remove_userprofile_user_delete_formsubmission_and_more'),
        ('home', '0003_sampleeventformpagewithmailinglistintegration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
