# Generated by Django 4.2.1 on 2023-05-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0085_remove_userprofile_user_delete_formsubmission_and_more'),
        ('home', '0003_mailinglistsubscribepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglistsubscribepage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Success Redirect Page'),
        ),
    ]
