# Generated by Django 4.2.1 on 2023-05-22 13:08

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0085_remove_userprofile_user_delete_formsubmission_and_more'),
        ('home', '0004_mailinglistsubscribepage_success_redirect_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleEventFormPageWithMailingListIntegration',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subscriber_json_data', models.TextField(blank=True, verbose_name='Mailing List Settings')),
                ('enable_mailing_list_subscription', models.BooleanField(default=False, verbose_name='Enable Mailing list subscription')),
                ('mailing_list_checkbox_label', models.CharField(blank=True, max_length=200, verbose_name='Mailing list checkbox label')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.forms.models.FormMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='mailinglistsubscribepage',
            name='double_optin',
            field=models.BooleanField(default=False, help_text='Check to use double opt-in process for new subscribers. If enabled, users must confirm their subscription via an email sent by MailChimp', verbose_name='Double Opt-In'),
        ),
        migrations.AlterField(
            model_name='mailinglistsubscribepage',
            name='success_redirect_page',
            field=models.ForeignKey(blank=True, help_text='Page to redirect to after successful submission.Leave unselected to show this page with an empty form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Success Redirect Page'),
        ),
    ]
