# Generated by Django 4.2.1 on 2024-02-29 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_sampleproductpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglistsubscribepage',
            name='success_redirect_page',
        ),
    ]
