# Generated by Django 4.2.1 on 2023-05-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_formfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleeventformpagewithmailinglistintegration',
            name='audience_list_id',
            field=models.CharField(blank=True, help_text='Select MailChimp Audience to use for this form', max_length=50, null=True, verbose_name='MailChimp Audience'),
        ),
        migrations.AlterField(
            model_name='mailinglistsubscribepage',
            name='list_id',
            field=models.CharField(help_text='Select MailChimp Audience to use for this form', max_length=50, verbose_name='MailChimp Audience'),
        ),
    ]
